apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-client
  template:
    metadata:
      labels:
        app: tcp-client
    spec:
      containers:
        - name: tcp-client
          image: tcp-user-timeout/client-server:latest
          command: ["/bin/sh"]
          args:
            - -c
            - LD_PRELOAD=/app/libsocket_wrapper.so TCP_USER_TIMEOUT_MS=5000 java -jar tcpapp.jar client tcp-server:12345
          imagePullPolicy: Never
          securityContext:
            runAsUser: 1000
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
