apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-server
  template:
    metadata:
      labels:
        app: tcp-server
    spec:
      containers:
        - name: server
          image: tcp-user-timeout/client-server:latest
          command: ["/bin/sh"]
          args:
            - -c
            - java -jar tcpapp.jar server 0.0.0.0:12345
          imagePullPolicy: Never
          ports:
            - containerPort: 12345
---
apiVersion: v1
kind: Service
metadata:
  name: tcp-server
spec:
  selector:
    app: tcp-server
  ports:
    - protocol: TCP
      port: 12345
      targetPort: 12345
